# Generated by Django 3.2.6 on 2021-11-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20211130_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='password',
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobile',
            field=models.TextField(),
        ),
    ]
