# Generated by Django 3.2.6 on 2021-11-30 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20211130_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='email',
            new_name='emails',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='firstname',
            new_name='firstnames',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='lastname',
            new_name='lastnames',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='mobile',
            new_name='mobiles',
        ),
        migrations.AddField(
            model_name='staff',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
