# Generated by Django 3.2.6 on 2021-11-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_staff_mobiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='mobiles',
            field=models.CharField(max_length=10),
        ),
    ]
