# Generated by Django 3.2.6 on 2021-11-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_staff_mobiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='last_login',
        ),
    ]
