# Generated by Django 3.2.6 on 2021-11-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_remove_staff_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='mobiles',
            new_name='phoneNumber',
        ),
    ]
