# Generated by Django 3.2.6 on 2021-11-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_rename_mobiles_staff_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
