# Generated by Django 3.2.6 on 2021-12-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Enquiry'},
        ),
    ]
