# Generated by Django 3.2.6 on 2021-12-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_contactus_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Enquiry',
        ),
    ]
