# Generated by Django 3.2.6 on 2021-12-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_enquiry_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={},
        ),
        migrations.AlterModelTable(
            name='enquiry',
            table=None,
        ),
    ]
