# Generated by Django 3.2.6 on 2021-12-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_aboutus_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=30)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('venue', models.CharField(default=None, max_length=30)),
                ('added_by', models.CharField(default=None, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Events',
                'db_table': 'events',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About-Us'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Blog'},
        ),
        migrations.AlterModelTable(
            name='aboutus',
            table='about_us',
        ),
        migrations.AlterModelTable(
            name='blog',
            table='blog',
        ),
    ]
