# Generated by Django 3.2.6 on 2021-12-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20211203_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='desctiption',
            new_name='description',
        ),
    ]
